# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-11 13:13
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='название')),
            ],
            options={
                'verbose_name': 'бренд',
                'verbose_name_plural': 'бренды',
            },
        ),
        migrations.CreateModel(
            name='BuyerType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='название')),
                ('one_s_id', models.CharField(max_length=36, unique=True, verbose_name='идентификатор 1С')),
            ],
            options={
                'verbose_name': 'тип покупателя',
                'verbose_name_plural': 'типы покупателей',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='название')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='categories', verbose_name='обложка')),
                ('one_s_ids', models.TextField(blank=True, null=True, verbose_name='Идентификаторы категорий в 1С')),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='shop.Category', verbose_name='родительская категория')),
                ('relations', mptt.fields.TreeManyToManyField(blank=True, related_name='_category_relations_+', to='shop.Category', verbose_name='связанные категории')),
            ],
            options={
                'verbose_name': 'категория',
                'verbose_name_plural': 'категории',
            },
        ),
        migrations.CreateModel(
            name='DecimalAttribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=3, max_digits=5, verbose_name='численное значение')),
            ],
            options={
                'verbose_name': 'атрибут числовой',
                'verbose_name_plural': 'атрибуты числовые',
            },
        ),
        migrations.CreateModel(
            name='DecimalFilter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='имя фильтра')),
                ('category', mptt.fields.TreeForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Category', verbose_name='категория')),
            ],
            options={
                'verbose_name': 'фильтр числовой',
                'verbose_name_plural': 'фильтры числовые',
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to='products', verbose_name='фотография')),
                ('position', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='позиция')),
            ],
            options={
                'verbose_name': 'фотография',
                'ordering': ['position'],
                'verbose_name_plural': 'фотографии',
            },
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='цена')),
                ('buyer_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.BuyerType', verbose_name='тип покупателя')),
            ],
            options={
                'verbose_name': 'цена товара',
                'verbose_name_plural': 'цены товара',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='наименование товара')),
                ('vendor_code', models.IntegerField(unique=True, verbose_name='артикул')),
                ('one_s_id', models.CharField(max_length=36, unique=True, verbose_name='идентификатор 1С')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='описание товара')),
                ('base_price', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='базовая цена')),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.Brand', verbose_name='бренд')),
                ('category', mptt.fields.TreeForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Category', verbose_name='категория')),
            ],
            options={
                'verbose_name': 'товар',
                'verbose_name_plural': 'товары',
            },
        ),
        migrations.CreateModel(
            name='Quantity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='количество')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Product', verbose_name='товар')),
            ],
            options={
                'verbose_name': 'остаток',
                'verbose_name_plural': 'остатки',
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='название')),
                ('one_s_id', models.CharField(max_length=36, unique=True, verbose_name='идентификатор 1С')),
            ],
            options={
                'verbose_name': 'магазин',
                'verbose_name_plural': 'магазины',
            },
        ),
        migrations.CreateModel(
            name='Variant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=64, verbose_name='значение')),
            ],
            options={
                'verbose_name': 'выбираемое значение атрибута',
                'verbose_name_plural': 'выбираемые значения атрибутов',
            },
        ),
        migrations.CreateModel(
            name='VariantAttribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'атрибут выбираемый',
                'verbose_name_plural': 'атрибуты выбираемые',
            },
        ),
        migrations.CreateModel(
            name='VariantFilter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='имя фильтра')),
                ('category', mptt.fields.TreeForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Category', verbose_name='категория')),
            ],
            options={
                'verbose_name': 'фильтр выборочный',
                'verbose_name_plural': 'фильтры выборочные',
            },
        ),
        migrations.AddField(
            model_name='variantattribute',
            name='attribute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.VariantFilter', verbose_name='атрибут'),
        ),
        migrations.AddField(
            model_name='variantattribute',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Product', verbose_name='товар'),
        ),
        migrations.AddField(
            model_name='variantattribute',
            name='values',
            field=models.ManyToManyField(blank=True, to='shop.Variant', verbose_name='значения'),
        ),
        migrations.AddField(
            model_name='variant',
            name='attribute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.VariantFilter'),
        ),
        migrations.AddField(
            model_name='quantity',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Store', verbose_name='магазин'),
        ),
        migrations.AddField(
            model_name='price',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Product', verbose_name='товар'),
        ),
        migrations.AddField(
            model_name='photo',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Product', verbose_name='товар'),
        ),
        migrations.AddField(
            model_name='decimalattribute',
            name='attribute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.DecimalFilter', verbose_name='атрибут'),
        ),
        migrations.AddField(
            model_name='decimalattribute',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Product', verbose_name='товар'),
        ),
        migrations.AlterUniqueTogether(
            name='variantfilter',
            unique_together=set([('name', 'category')]),
        ),
        migrations.AlterUniqueTogether(
            name='variantattribute',
            unique_together=set([('product', 'attribute')]),
        ),
        migrations.AlterUniqueTogether(
            name='quantity',
            unique_together=set([('store', 'product')]),
        ),
        migrations.AlterUniqueTogether(
            name='price',
            unique_together=set([('product', 'buyer_type')]),
        ),
        migrations.AlterUniqueTogether(
            name='decimalfilter',
            unique_together=set([('name', 'category')]),
        ),
        migrations.AlterUniqueTogether(
            name='decimalattribute',
            unique_together=set([('product', 'attribute')]),
        ),
    ]
