# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-12 06:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20170411_2040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=128, unique=True, verbose_name='наименование товара'),
        ),
        migrations.AlterField(
            model_name='product',
            name='vendor_code',
            field=models.IntegerField(verbose_name='артикул'),
        ),
    ]
