# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-12 07:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20170412_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=128, verbose_name='наименование товара'),
        ),
    ]
