# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-13 05:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20170412_1234'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-price'], 'verbose_name': 'товар', 'verbose_name_plural': 'товары'},
        ),
    ]
