# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-13 05:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20170413_1055'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-base_price'], 'verbose_name': 'товар', 'verbose_name_plural': 'товары'},
        ),
    ]
