# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-13 07:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_auto_20170413_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='vendor_code',
            field=models.IntegerField(blank=True, null=True, verbose_name='артикул'),
        ),
    ]
