# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-23 17:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20170423_1639'),
        ('shop', '0009_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.DeliveryAddress', verbose_name='адрес доставки'),
        ),
    ]
