# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-23 23:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_auto_20170423_2303'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_paid',
            field=models.BooleanField(choices=[(False, 'Не оплачено'), (True, 'Оплачено')], default=False, verbose_name='статус оплаты'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[(1, 'заказано'), (2, 'принято'), (0, 'отложено'), (3, 'доставлено')], default='ordered', max_length=16, verbose_name='статус заказа'),
        ),
    ]
