# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-24 07:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_auto_20170424_0459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='is_paid',
            field=models.BooleanField(default=False, verbose_name='оплачено'),
        ),
        migrations.AlterField(
            model_name='order',
            name='quantity',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='кол-во'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('deferred', 'отложено'), ('ordered', 'заказано'), ('accepted', 'принято'), ('shipped', 'отправлено'), ('delivered', 'доставлено')], default='ordered', max_length=16, verbose_name='статус'),
        ),
    ]
