# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-26 10:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_auto_20170426_1103'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliveryaddress',
            name='buyer',
        ),
        migrations.RemoveField(
            model_name='order',
            name='delivery_address',
        ),
        migrations.DeleteModel(
            name='DeliveryAddress',
        ),
    ]
