# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-26 11:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0015_auto_20170426_1516'),
    ]

    operations = [
        migrations.CreateModel(
            name='LegalEntity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legal_entity', models.CharField(blank=True, max_length=128, verbose_name='юридическое лицо')),
                ('taxpayer_id', models.DecimalField(decimal_places=0, max_digits=10, unique=True, verbose_name='ИНН')),
                ('reason_code', models.DecimalField(decimal_places=0, max_digits=9, unique=True, verbose_name='КПП')),
                ('bank', models.CharField(blank=True, max_length=128, verbose_name='банк клиента')),
                ('bank_id', models.DecimalField(decimal_places=0, max_digits=9, unique=True, verbose_name='БИК')),
                ('bank_account', models.DecimalField(decimal_places=0, max_digits=20, unique=True, verbose_name='банковский счёт клиента')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='клиент')),
            ],
            options={
                'verbose_name_plural': 'юридические лица',
                'verbose_name': 'юридическое лицо',
            },
        ),
    ]
