# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-26 11:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_legalentity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='legalentity',
            name='legal_entity',
        ),
        migrations.AddField(
            model_name='legalentity',
            name='name',
            field=models.CharField(default=1, max_length=128, verbose_name='юридическое лицо'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='legalentity',
            name='bank',
            field=models.CharField(max_length=128, verbose_name='банк клиента'),
        ),
        migrations.AlterField(
            model_name='legalentity',
            name='bank_account',
            field=models.DecimalField(decimal_places=0, max_digits=20, verbose_name='банковский счёт клиента'),
        ),
        migrations.AlterField(
            model_name='legalentity',
            name='reason_code',
            field=models.DecimalField(decimal_places=0, max_digits=9, verbose_name='КПП'),
        ),
    ]
