# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-27 06:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_auto_20170426_1636'),
    ]

    operations = [
        migrations.AddField(
            model_name='legalentity',
            name='delivery_address',
            field=models.CharField(blank=True, max_length=128, verbose_name='адрес доставки'),
        ),
        migrations.AlterField(
            model_name='legalentity',
            name='bank_account',
            field=models.DecimalField(decimal_places=0, max_digits=20, verbose_name='рассчётный счёт'),
        ),
    ]
