# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-27 07:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_auto_20170427_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legalentity',
            name='bank_account',
            field=models.CharField(max_length=20, verbose_name='рассчётный счёт'),
        ),
        migrations.AlterField(
            model_name='legalentity',
            name='bank_id',
            field=models.CharField(max_length=9, unique=True, verbose_name='БИК'),
        ),
        migrations.AlterField(
            model_name='legalentity',
            name='reason_code',
            field=models.CharField(max_length=9, verbose_name='КПП'),
        ),
        migrations.AlterField(
            model_name='legalentity',
            name='taxpayer_id',
            field=models.CharField(max_length=10, unique=True, verbose_name='ИНН'),
        ),
    ]
