# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-27 07:38
from __future__ import unicode_literals

from django.db import migrations, models
import shop.models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0019_auto_20170427_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legalentity',
            name='taxpayer_id',
            field=models.CharField(max_length=12, unique=True, verbose_name='ИНН'),
        ),
    ]
