# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-28 06:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0020_auto_20170427_1238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legalentity',
            name='bank_id',
            field=models.CharField(max_length=9, verbose_name='БИК'),
        ),
        migrations.AlterField(
            model_name='legalentity',
            name='name',
            field=models.CharField(max_length=128, verbose_name='название'),
        ),
        migrations.AlterField(
            model_name='legalentity',
            name='taxpayer_id',
            field=models.CharField(help_text='Идентификационный номер налогоплательщика', max_length=12, unique=True, verbose_name='ИНН'),
        ),
    ]
