# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-28 11:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0021_auto_20170428_1154'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='legalentity',
            name='delivery_address',
        ),
    ]
