# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-28 11:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0022_remove_legalentity_delivery_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery',
            field=models.CharField(blank=True, max_length=128, verbose_name='адрес доставки'),
        ),
        migrations.AlterField(
            model_name='legalentity',
            name='bank',
            field=models.CharField(max_length=128, verbose_name='банк для рассчётов'),
        ),
        migrations.AlterField(
            model_name='legalentity',
            name='taxpayer_id',
            field=models.CharField(max_length=12, unique=True, verbose_name='ИНН'),
        ),
    ]
