# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-06 14:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0025_auto_20170428_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery',
            field=models.TextField(blank=True, max_length=256, verbose_name='адрес доставки'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.Category', verbose_name='категория'),
        ),
    ]
