# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-11 10:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0026_auto_20170506_1949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='one_s_id',
            field=models.CharField(max_length=36, null=True, unique=True, verbose_name='идентификатор 1С'),
        ),
        migrations.AlterField(
            model_name='product',
            name='vendor_code',
            field=models.CharField(max_length=36, null=True, verbose_name='артикул'),
        ),
    ]
