# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-13 10:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0028_auto_20170511_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='vendor_code',
            field=models.CharField(blank=True, max_length=36, null=True, verbose_name='артикул'),
        ),
    ]
