# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-19 07:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0032_auto_20170519_1210'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
        migrations.AddField(
            model_name='receipt',
            name='status',
            field=models.CharField(choices=[('deferred', 'отложено'), ('ordered', 'заказано'), ('accepted', 'принято'), ('shipped', 'отправлено'), ('delivered', 'доставлено')], default='ordered', max_length=16, verbose_name='статус'),
        ),
    ]
