# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-19 07:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0033_auto_20170519_1227'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='buyer',
        ),
        migrations.RemoveField(
            model_name='order',
            name='delivery',
        ),
        migrations.AddField(
            model_name='receipt',
            name='buyer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='клиент'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='receipt',
            name='delivery',
            field=models.TextField(blank=True, max_length=256, verbose_name='адрес доставки'),
        ),
    ]
