# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-19 07:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0034_auto_20170519_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='receipt',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='shop.Receipt', verbose_name='счёт на оплату'),
            preserve_default=False,
        ),
    ]
