# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-19 07:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0035_auto_20170519_1253'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='is_accepted',
            field=models.BooleanField(default=False, verbose_name='принято'),
        ),
    ]
