# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-19 11:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0037_remove_receipt_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='legal_entity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.LegalEntity', verbose_name='юридическое лицо'),
        ),
    ]
