# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-21 15:14
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0038_receipt_legal_entity'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='really_up_to',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 24, 15, 14, 23, 796222, tzinfo=utc)),
        ),
    ]
