# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-21 15:16
from __future__ import unicode_literals

from django.db import migrations, models
import shop.models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0039_receipt_really_up_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='really_up_to',
            field=models.DateTimeField(default=shop.models.Receipt.get_really_up_to),
        ),
    ]
