# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-21 16:47
from __future__ import unicode_literals

from django.db import migrations, models
import shop.models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0040_auto_20170521_2016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='really_up_to',
            field=models.DateTimeField(default=shop.models.Receipt.get_really_up_to, verbose_name='действительно до'),
        ),
    ]
