# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-22 11:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0041_auto_20170521_2147'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='receipt',
            options={'ordering': ['-id'], 'verbose_name': 'счёт на оплату', 'verbose_name_plural': 'счета на оплату'},
        ),
    ]
