# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-23 06:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0042_auto_20170522_1657'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('processed', 'в обработке'), ('accepted', 'принято'), ('shipped', 'отгружено'), ('canceled', 'отменено')], default='processed', max_length=32, verbose_name='статус позиции заказа'),
        ),
        migrations.AddField(
            model_name='receipt',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='базовая цена'),
        ),
    ]
