# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-23 06:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0043_auto_20170523_1123'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receipt',
            name='is_accepted',
        ),
        migrations.RemoveField(
            model_name='receipt',
            name='is_paid',
        ),
    ]
