# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-30 08:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0044_auto_20170523_1130'),
    ]

    operations = [
        migrations.RenameField(
            model_name='decimalattribute',
            old_name='attribute',
            new_name='filter',
        ),
        migrations.AlterField(
            model_name='receipt',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='внесённая сумма'),
        ),
        migrations.AlterUniqueTogether(
            name='decimalattribute',
            unique_together=set([('product', 'filter')]),
        ),
    ]
