# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-30 08:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0045_auto_20170530_1345'),
    ]

    operations = [
        migrations.RenameField(
            model_name='variantattribute',
            old_name='attribute',
            new_name='filter',
        ),
        migrations.AlterUniqueTogether(
            name='variantattribute',
            unique_together=set([('product', 'filter')]),
        ),
    ]
