# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-30 09:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0046_auto_20170530_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='decimalattribute',
            name='value',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=5, verbose_name='численное значение'),
        ),
    ]
