# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-30 11:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0047_auto_20170530_1449'),
    ]

    operations = [
        migrations.RenameField(
            model_name='variant',
            old_name='attribute',
            new_name='filter',
        ),
    ]
