# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-31 11:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0054_auto_20170531_1641'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='decimalattribute',
            options={'verbose_name': 'атрибут-число', 'verbose_name_plural': 'атрибуты-число'},
        ),
        migrations.AlterModelOptions(
            name='decimalfilter',
            options={'verbose_name': 'фильтр-число', 'verbose_name_plural': 'фильтры-число'},
        ),
        migrations.AlterModelOptions(
            name='rangeattribute',
            options={'verbose_name': 'атрибут-диапазон', 'verbose_name_plural': 'атрибуты-диапазон'},
        ),
        migrations.AlterModelOptions(
            name='rangefilter',
            options={'verbose_name': 'фильтр-диапазон', 'verbose_name_plural': 'фильтры-диапазон'},
        ),
        migrations.AlterModelOptions(
            name='variant',
            options={'verbose_name': 'значение фильтра-выбор', 'verbose_name_plural': 'значения фильтра-выбор'},
        ),
        migrations.AlterModelOptions(
            name='variantattribute',
            options={'verbose_name': 'атрибут-выбор', 'verbose_name_plural': 'атрибуты-выбор'},
        ),
        migrations.AlterModelOptions(
            name='variantfilter',
            options={'verbose_name': 'фильтр-выбор', 'verbose_name_plural': 'фильтры-выбор'},
        ),
        migrations.AlterField(
            model_name='decimalattribute',
            name='value',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=5, verbose_name='значение'),
        ),
        migrations.AlterField(
            model_name='decimalfilter',
            name='name',
            field=models.CharField(max_length=64, verbose_name='название фильтра'),
        ),
        migrations.AlterField(
            model_name='rangefilter',
            name='name',
            field=models.CharField(max_length=64, verbose_name='название фильтра'),
        ),
        migrations.AlterField(
            model_name='variantfilter',
            name='name',
            field=models.CharField(max_length=64, verbose_name='название фильтра'),
        ),
    ]
