# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-01 07:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0055_auto_20170531_1652'),
    ]

    operations = [
        migrations.AddField(
            model_name='decimalfilter',
            name='unit',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='единица измерения'),
        ),
        migrations.AddField(
            model_name='rangefilter',
            name='unit',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='единица измерения'),
        ),
        migrations.AddField(
            model_name='variantfilter',
            name='unit',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='единица измерения'),
        ),
    ]
