# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-04 03:10
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0058_auto_20170601_1231'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='legalentity',
            name='bank',
        ),
        migrations.RemoveField(
            model_name='legalentity',
            name='bank_id',
        ),
        migrations.AddField(
            model_name='legalentity',
            name='phone',
            field=models.DecimalField(decimal_places=0, default=1234567890, error_messages={'min_value': 'Номер телефона указывается без восьмёрки, должен содержать 10 цифр и не должен начинаться с 0', 'unique': 'Пользователь с таким номера телефона уже существует'}, max_digits=10, validators=[django.core.validators.MaxValueValidator(9999999999), django.core.validators.MinValueValidator(1000000000)], verbose_name='номер телефона'),
            preserve_default=False,
        ),
    ]
