# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-04 03:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0059_auto_20170604_0810'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='legalentity',
            name='bank_account',
        ),
        migrations.AddField(
            model_name='legalentity',
            name='legal_address',
            field=models.TextField(blank=True, max_length=256, verbose_name='юридический адрес'),
        ),
    ]
