# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-10 07:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0063_auto_20170610_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='decimalattribute',
            name='value',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=5, verbose_name='значение'),
        ),
    ]
