# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-11 10:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0064_auto_20170610_1246'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='depth',
            field=models.IntegerField(blank=True, null=True, verbose_name='глубина, мм.'),
        ),
        migrations.AddField(
            model_name='product',
            name='height',
            field=models.IntegerField(blank=True, null=True, verbose_name='высота, мм.'),
        ),
        migrations.AddField(
            model_name='product',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True, verbose_name='вес с упаковкой (брутто), кг.'),
        ),
        migrations.AddField(
            model_name='product',
            name='width',
            field=models.IntegerField(blank=True, null=True, verbose_name='ширина, мм.'),
        ),
        migrations.AlterField(
            model_name='decimalattribute',
            name='value',
            field=models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=9, verbose_name='значение'),
        ),
    ]
