# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-11 10:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0066_product_volume'),
    ]

    operations = [
        migrations.AddField(
            model_name='decimalfilter',
            name='position',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='позиция'),
        ),
        migrations.AddField(
            model_name='rangefilter',
            name='position',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='позиция'),
        ),
        migrations.AddField(
            model_name='variant',
            name='position',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='позиция'),
        ),
        migrations.AddField(
            model_name='variantfilter',
            name='position',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='позиция'),
        ),
    ]
