# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-04 06:03
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='заголовок страницы')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='содержание страницы')),
            ],
            options={
                'verbose_name_plural': 'произвольные страницы',
                'verbose_name': 'произвольная страницы',
            },
        ),
    ]
