# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-23 09:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.CharField(blank=True, max_length=128, verbose_name='адрес доставки'),
        ),
    ]
