# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-23 11:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deliveryaddress',
            old_name='user',
            new_name='buyer',
        ),
    ]
