# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-23 18:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_auto_20170423_2303'),
        ('users', '0003_auto_20170423_1639'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliveryaddress',
            name='buyer',
        ),
        migrations.DeleteModel(
            name='DeliveryAddress',
        ),
    ]
