# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-23 23:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20170423_2303'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_seller',
            field=models.BooleanField(default=False, help_text='Отметьте, если пользователь является менеджером по продажам.', verbose_name='менеджер по продажам'),
        ),
    ]
