# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-24 10:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20170424_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_seller',
            field=models.BooleanField(default=False, help_text='Отметьте, чтобы пользователь мог взаимодействовать только со своими клиентами.', verbose_name='менеджер по продажам'),
        ),
    ]
