# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-26 10:16
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20170426_1128'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='delivery_address',
            field=models.CharField(blank=True, max_length=128, verbose_name='адрес доставки'),
        ),
        migrations.AlterField(
            model_name='user',
            name='buyer_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.BuyerType', verbose_name='тип клиента'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_seller',
            field=models.BooleanField(default=False, help_text='Отметьте, чтобы пользователь мог взаимодействовать только со своими клиентами.', verbose_name='менеджер'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.DecimalField(decimal_places=0, error_messages={'min_value': 'Номер телефона указывается без восьмёрки, должен содержать 10 цифр и не должен начинаться с 0', 'unique': 'Пользователь с таким номера телефона уже существует'}, max_digits=10, unique=True, validators=[django.core.validators.MaxValueValidator(9999999999), django.core.validators.MinValueValidator(1000000000)], verbose_name='телефон (без восьмёрки)'),
        ),
        migrations.AlterField(
            model_name='user',
            name='seller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='buyer_set', to=settings.AUTH_USER_MODEL, verbose_name='менеджер клиента'),
        ),
        migrations.AlterField(
            model_name='user',
            name='wholesale_buyer_request',
            field=models.BooleanField(default=False, verbose_name='заявка оптовика'),
        ),
    ]
