# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-28 11:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20170427_1143'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='default_delivery_address',
            field=models.CharField(blank=True, max_length=128, verbose_name='адрес доставки по-умолчанию'),
        ),
    ]
