# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-28 11:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_user_default_delivery_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='default_delivery_address',
            new_name='default_delivery',
        ),
    ]
